generatorName: go
packageName: apiv3_7
packageVersion: 3.7.8

gitHost: github.com
gitUserId: jqueuniet
gitRepoId: netbox-go

inputSpec: schemas/patched-3.7.8.yaml
outputDir: apiv3_7

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: "true"

additionalProperties:
  generateInterfaces: true
  isGoSubmodule: true
  withGoMod: false
  disallowAdditionalPropertiesIfNotPresent: false
  useDefaultValuesForRequiredVars: true
  enumClassPrefix: true
