generatorName: go
packageName: apiv4_1
packageVersion: 4.1.6

gitHost: github.com
gitUserId: jqueuniet
gitRepoId: netbox-go

inputSpec: schemas/patched-4.1.6.yaml
outputDir: apiv4_1

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

additionalProperties:
  generateInterfaces: true
  isGoSubmodule: true
  withGoMod: false
  disallowAdditionalPropertiesIfNotPresent: false
  useDefaultValuesForRequiredVars: true
  enumClassPrefix: true