generatorName: go
packageName: v3_5
packageVersion: 3.5.9

gitHost: github.com
gitUserId: jqueuniet
gitRepoId: netbox-go

inputSpec: schemas/patched-3.5.9.yaml
outputDir: v3_5

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

additionalProperties:
  generateInterfaces: true
  isGoSubmodule: true
  withGoMod: false
  disallowAdditionalPropertiesIfNotPresent: false
  useDefaultValuesForRequiredVars: true
  enumClassPrefix: true