generatorName: go
packageName: apiv4_0
packageVersion: 4.0.11

gitHost: github.com
gitUserId: jqueuniet
gitRepoId: netbox-go

inputSpec: schemas/patched-4.0.11.yaml
outputDir: apiv4_0

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: "true"

additionalProperties:
  generateInterfaces: true
  isGoSubmodule: true
  withGoMod: false
  disallowAdditionalPropertiesIfNotPresent: false
  useDefaultValuesForRequiredVars: true
  enumClassPrefix: true
